// generated-version.js — auto-generated by CI (unitune-app/scripts/parse-changelog.js)
// Do NOT edit manually. To update locally without CI:
//   node scripts/parse-changelog.js > /tmp/v.json
//   echo "export default $(cat /tmp/v.json);" > generated-version.js
//   wrangler deploy
export default {
  "latest_version": "1.5.0",
  "latest_build": 17,
  "force_update": false,
  "min_supported_build": 1,
  "whats_new": [
    {
      "icon": "system_update",
      "title": "Update Notifications",
      "body": "UniTune now notifies you when a new version is available."
    },
    {
      "icon": "auto_awesome",
      "title": "What's New",
      "body": "After each update you'll see the highlights once."
    },
    {
      "icon": "rocket_launch",
      "title": "Faster Releases",
      "body": "New versions are built and published automatically."
    },
    {
      "icon": "privacy_tip",
      "title": "Privacy First",
      "body": "The update check sends no user data, just an anonymous version request."
    }
  ],
  "update_urls": {
    "playstore": "https://play.google.com/store/apps/details?id=de.unitune.unitune",
    "github": "https://github.com/FlazeIGuess/unitune/releases/latest",
    "appstore": "https://apps.apple.com/app/unitune/id0000000000"
  },
  "changelog_url": "https://github.com/FlazeIGuess/unitune/blob/main/unitune-app/CHANGELOG.md"
}
